service: addresscontrol
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  environment:
    TOPIC_ARN: 'arn:aws:sns:us-east-1:711459267474:NotifyCourier'
    TARGET_ARN: 'arn:aws:sns:us-east-1:711459267474:NotifyCourier:endpoint'

functions:
  AllAddress:
    handler: handler.AllAddress
    events:
      - http:
          method: get
          path: scanaddress
          cors: true 
  OneAddress:
    handler: handler.OneAddress
    events:
      - http:
          method: post
          path: getaddress
          cors: true 
  sendEmail:
    handler: senderEmailTask.sendEmail
    events:
      - http:
          method: post
          path: sendemail
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ses:*
        Resource: '*'

plugins:
  - serverless-iam-roles-per-function
  
